# Generated by Django 5.0.3 on 2024-05-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
