# Generated by Django 5.0.3 on 2024-05-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='purchased_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sold_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
