# Generated by Django 5.0.3 on 2024-04-24 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_alter_product_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
