# Generated by Django 5.0.3 on 2024-05-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rw_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rw_order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
