# Generated by Django 5.0.3 on 2024-05-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rw_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rw_order',
            old_name='is_rechart',
            new_name='is_recharge',
        ),
    ]
