# Generated by Django 5.0.3 on 2024-05-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_is_rechart_rw_order_is_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='rw_order',
            name='user_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
